[package]
name = "java2flowchart"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.32"
fontdb = "0.23.0"
image = "0.25.8"
imageproc = "0.25.0"
phf = { version = "0.13.1", features = ["macros"] }
